# Generated by Django 5.1.7 on 2025-03-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniHaven', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isSpecialist',
            field=models.BooleanField(default=False),
        ),
    ]
